### ISSUE TITLE
利用自己的ip刷太慢了，一分钟内每篇文章只能刷洗你一次，有啥意义！

### ISSUE THREAD

**Issue by Mrliu-l** [1015770492/autoRefreshCSDN#1]

**Comment by 1015770492** [comment]
1.  首先一点，csdn做了永久封ip的设置功能，如果用同一个ip对同一篇文章不停的访问，那么就会被封永久ip
2. 其次：代理ip需要花钱，而且非常不稳定。如果是用网上免费的代理ip，那么消耗的时间实际上更长基本上没有用的代理ip。
刷访问量如果想要刷的更多，那么你就多写些文章，可以提高刷的总访问量

因此我这里不建议使用代理ip刷，注意ip是公网ip，如果是局域网最终使用的ip还是同一个公网ip

### 理论上一天能刷的访问量=文章数 * 24*3600/一分钟的间隔
如果你写了500篇文章一天增加的访问量是
500 * 24 *3600 /60 大概是72万的访问量
***

到现在我已经刷了1500万访问量了
我的博客地址[诗水人间](https://blog.csdn.net/qq_41813208)


### 另外我写了`点赞`功能，`收藏`暂时不做，
最近又很多事情要做，日后将收藏，登录等一系列功能都作为。
我的最终目的是自己做一个博客系统然后利用我这里写的api到时候之间调用作为工具类，进行发布文章同步文章等

**Comment by 1015770492** [comment]
建议你不要刷的太快了，刷的太快说不准csdn会永久封账号、得不偿失。

**Comment by Mrliu-l** [comment]
> 建议你不要刷的太快了，刷的太快说不准csdn会永久封账号、得不偿失。

csdn同一个ip可以对同一片文章多次点赞吗？

**Comment by 1015770492** [comment]
不可以，点赞是需要登录csdn用户的，也就是如果没有cookie则不能点赞。

其次同一个用户多次调用点赞就相当于`取消点赞了`。因此我的做法是使用用户的cookie模拟这个用户去访问文章，看获得内容是`已赞`还是`点赞`

如果是点赞，说明前面没有点赞，那么我就调用点赞接口，进行点赞

**Comment by Mrliu-l** [comment]
> 不可以，点赞是需要登录csdn用户的，也就是如果没有cookie则不能点赞。
> 
> 其次同一个用户多次调用点赞就相当于`取消点赞了`。因此我的做法是使用用户的cookie模拟这个用户去访问文章，看获得内容是`已赞`还是`点赞`
> 
> 如果是点赞，说明前面没有点赞，那么我就调用点赞接口，进行点赞

你这里边的“用户的cookie”指的是自己的cookie吗？那也就是说每篇文章最多点赞一次了？

**Comment by 1015770492** [comment]
那是肯定了，一个用户只能点赞一次。点赞是加积分的一个赞10分，而且每一个用户一天内的点赞次数是有上限的，如果是新的csdn账号一般是30个左右，等级高的可能是60个赞。

**Comment by 1015770492** [comment]
![image](https://user-images.githubusercontent.com/43501801/92245560-226b1f80-eef7-11ea-8b1f-a55ac58cb5de.png)

**Comment by 1015770492** [comment]
你也可以使用其它人的cookie，关键是人家愿意给你cookie数据。
